version: "3.8"

services:
  san-site:
    image: san-automation-site:latest
    environment:
      - NODE_ENV=production
    networks:
      - san-net
    deploy:
      replicas: 1
      placement:
        constraints:

          - node.hostname == vmi3030097      
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.san-site.rule=Host(`www.san-automation.com.br`)"
        - "traefik.http.routers.san-site.entrypoints=websecure"
        - "traefik.http.routers.san-site.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.san-site.service=san-site"
        - "traefik.http.services.san-site.loadbalancer.server.port=3000"
        - "traefik.http.services.san-site.loadbalancer.passHostHeader=true"

networks:
  san-net:
    external: true
